// Regenerate TeX italic corrections from the pinned KaTeX package. Fontkit
// supplies outlines and advances; an ink overhang is not a TeX italic correction.
// This internal dependency is read only by this maintenance script.
import { dirname, join, basename } from 'node:path'
import { fileURLToPath } from 'node:url'
import { MATH_FONT_PATHS } from '../src/fonts'
import symbols from '../src/symbols'

const root = dirname(fileURLToPath(import.meta.resolve('katex/package.json')))
const { version } = await Bun.file(join(root, 'package.json')).json()
if (version !== '0.16.47') throw new Error(`Review the parser/font adapter before updating KaTeX ${version}`)
const { default: data } = await import(join(root, 'src/fontMetricsData.js')) as {
  default: Record<string, Record<string, number[]>>
}
const faces = Object.entries(MATH_FONT_PATHS).map(([face, path]) => {
  const name = basename(path, '.ttf').replace(/^KaTeX_/, '')
  const entries = Object.entries(data[name]!).filter(([, metrics]) => metrics[2] !== 0)
    .map(([code, metrics]) => [String.fromCodePoint(Number(code)), metrics[2]])
  return `  ${JSON.stringify(face)}: ${JSON.stringify(Object.fromEntries(entries))},`
})
await Bun.write(new URL('../src/italic.ts', import.meta.url),
  `// Generated by scripts/update-font-data.ts from KaTeX ${version}.\n`
  + '// MIT; see THIRD_PARTY_NOTICES.md. Values are in em, independently of outline ink.\n'
  + 'const MATH_ITALIC: Readonly<Record<string, Readonly<Record<string, number>>>> = {\n'
  + faces.join('\n') + '\n}\n\nexport { MATH_ITALIC }\n')

const operators = new Set(Object.values(symbols.math).filter(entry => entry.family === 'op-token').map(entry => entry.replace))
const operator_faces = ['Size1-Regular', 'Size2-Regular'].map(face => {
  const entries = Object.entries(data[face]!).filter(([code]) => operators.has(String.fromCodePoint(Number(code))))
    .map(([code, metrics]) => [String.fromCodePoint(Number(code)), [metrics[1], metrics[0]]])
  return `  ${JSON.stringify('KaTeX_' + face.replace('-Regular', ''))}: ${JSON.stringify(Object.fromEntries(entries))},`
})
await Bun.write(new URL('../src/operator-metrics.ts', import.meta.url),
  `// Generated by scripts/update-font-data.ts from KaTeX ${version}.\n`
  + '// MIT; see THIRD_PARTY_NOTICES.md. Logical [height, depth] in em, independent of ink.\n'
  + 'const OPERATOR_METRICS: Readonly<Record<string, Readonly<Record<string, readonly [number, number]>>>> = {\n'
  + operator_faces.join('\n') + '\n}\n\nexport { OPERATOR_METRICS }\n')
