// Regenerate TeX italic corrections from the pinned KaTeX package. Fontkit
// supplies outlines and advances; an ink overhang is not a TeX italic correction.
// This internal dependency is read only by this maintenance script.
import { dirname, join, basename } from 'node:path'
import { fileURLToPath } from 'node:url'
import { MATH_FONT_PATHS } from '../src/fonts'

const root = dirname(fileURLToPath(import.meta.resolve('katex/package.json')))
const { version } = await Bun.file(join(root, 'package.json')).json()
if (version !== '0.16.47') throw new Error(`Review the parser/font adapter before updating KaTeX ${version}`)
const { default: data } = await import(join(root, 'src/fontMetricsData.js')) as {
  default: Record<string, Record<string, number[]>>
}
const faces = Object.entries(MATH_FONT_PATHS).map(([face, path]) => {
  const name = basename(path, '.ttf').replace(/^KaTeX_/, '')
  const entries = Object.entries(data[name]!).filter(([, metrics]) => metrics[2] !== 0)
    .map(([code, metrics]) => [String.fromCodePoint(Number(code)), metrics[2]])
  return `  ${JSON.stringify(face)}: ${JSON.stringify(Object.fromEntries(entries))},`
})
await Bun.write(new URL('../src/italic.ts', import.meta.url),
  `// Generated by scripts/update-font-data.ts from KaTeX ${version}.\n`
  + '// MIT; see THIRD_PARTY_NOTICES.md. Values are in em, independently of outline ink.\n'
  + 'const MATH_ITALIC: Readonly<Record<string, Readonly<Record<string, number>>>> = {\n'
  + faces.join('\n') + '\n}\n\nexport { MATH_ITALIC }\n')
